# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Build Agent

variables:
  majorVersion: '1'
  minorVersion: '1'
  patchVersion: '0'

stages:
- stage: Build
  displayName: 'Building jar'
  jobs:
  - job: BuildJar
    displayName: 'Running the job to build the jar'
    pool:
      name: Build Agent

    steps:
    - script: |
        mvn clean package
        cp target/*.jar $(Build.ArtifactStagingDirectory)
      displayName: 'Jar build'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'Buildjar'  # Specify a unique artifact name
        displayName: 'Publish Buildjar artifact'

- stage: Release
  displayName: 'Releasing the Jar'
  jobs: 
  - deployment: deployment
    environment: 'deployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'Buildjar'  # Specify the same artifact name used in the TrivyScan stage
              path: $(Build.ArtifactStagingDirectory)
            displayName: 'Download BuildJar artifact'
      
          - script: |
              java -jar $(Build.ArtifactStagingDirectory)/*.jar
